import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Header, Card, Button } from '../../components';
import { useTranslation } from '../../i18n/useTranslation';

export const PrivacyPolicy = () => {
  const navigate = useNavigate();
  const { t, locale } = useTranslation();

  return (
    <div className="min-h-screen bg-bg-light pb-12">
      <Header showBack onBack={() => navigate(-1)} />
      <section className="bg-primary py-8 px-4 text-center">
        <h1 className="text-3xl font-bold text-text-dark">{t('compliance.privacyPolicy')}</h1>
      </section>
      <section className="max-w-3xl mx-auto px-4 py-8">
        <Card className="prose max-w-none text-text-dark">
          {locale === 'kn' ? (
            <div className="space-y-6 text-sm leading-relaxed">
              <p className="font-bold">ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಿದ್ದು: ಜೂನ್ 7, 2026</p>
              <p>MilkMaatu ಅಪ್ಲಿಕೇಶನ್ ಕರ್ನಾಟಕದ ಹೈನುಗಾರರ ಸುಲಭ ಸೇವೆಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ. ಈ ಗೌಪ್ಯತಾ ನೀತಿಯು ನಿಮ್ಮ ಮಾಹಿತಿ ಸಂಗ್ರಹಣೆ, ಸಂಗ್ರಹಿಸುವ ಕಾರಣ ಮತ್ತು ಅದರ ಸುರಕ್ಷತೆಯ ವಿವರಗಳನ್ನು ಒದಗಿಸುತ್ತದೆ.</p>
              
              <div>
                <h3 className="text-lg font-bold mb-2">೧. ನಾವು ಸಂಗ್ರಹಿಸುವ ಮಾಹಿತಿ</h3>
                <ul className="list-disc pl-5 space-y-1">
                  <li><strong>ವೈಯಕ್ತಿಕ ವಿವರಗಳು:</strong> ನೋಂದಣಿ ಸಮಯದಲ್ಲಿ ನಿಮ್ಮ ಹೆಸರು, ಮೊಬೈಲ್ ಸಂಖ್ಯೆ, ವಿಳಾಸ ಮತ್ತು ಗ್ರಾಮದ ಹೆಸರು.</li>
                  <li><strong>ಜಾನುವಾರುಗಳ ಚಿತ್ರಗಳು:</strong> ಸಂತೆಯಲ್ಲಿ ಮಾರಾಟಕ್ಕಾಗಿ ನೀವು ಅಪ್ಲೋಡ್ ಮಾಡುವ ಹಸು/ಎಮ್ಮೆಗಳ ಲೈವ್ ಫೋಟೋಗಳು.</li>
                  <li><strong>AI ಚಾಟ್ ಇತಿಹಾಸ:</strong> ನಂದಿನಿ AI ಸಹಾಯಕಿಯೊಂದಿಗೆ ನೀವು ನಡೆಸುವ ಪ್ರಶ್ನೋತ್ತರ ಇತಿಹಾಸ.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-lg font-bold mb-2">೨. ಮಾಹಿತಿ ಸಂಗ್ರಹಣೆಯ ಉದ್ದೇಶ</h3>
                <p>ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಕೆಳಗಿನ ಕಾರಣಗಳಿಗಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ:</p>
                <ul className="list-disc pl-5 space-y-1">
                  <li>ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು WhatsApp OTP ಮೂಲಕ ದೃಢೀಕರಿಸಲು.</li>
                  <li>ಮೇವು ವಿತರಣೆ ಮತ್ತು ಜಾನುವಾರು ಸಂತೆ ಖರೀದಿ-ಮಾರಾಟ ಸುಗಮಗೊಳಿಸಲು.</li>
                  <li>ನಂದಿನಿ AI ಮೂಲಕ ನಿಖರ ಹೈನುಗಾರಿಕೆ ಮಾಹಿತಿ ಒದಗಿಸಲು.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-lg font-bold mb-2">೩. ಮಾಹಿತಿ ಸುರಕ್ಷತೆ ಮತ್ತು ಸಂಗ್ರಹಣೆ</h3>
                <p>ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್‌ಗಳನ್ನು ಉನ್ನತ ಗುಣಮಟ್ಟದ ಎನ್‌ಕ್ರಿಪ್ಶನ್ (bcrypt) ಬಳಸಿ ಸುರಕ್ಷಿತವಾಗಿ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಸಂಗ್ರಹಿಸಲಾಗುತ್ತದೆ.</p>
              </div>

              <div>
                <h3 className="text-lg font-bold mb-2">೪. ಮಾಹಿತಿ ಅಳಿಸುವಿಕೆ (Account Deletion)</h3>
                <p>ಬಳಕೆದಾರರಿಗೆ ತಮ್ಮ ಖಾತೆಯನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ಅಳಿಸುವ ಹಕ್ಕಿದೆ. ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ "ಖಾತೆಯನ್ನು ಅಳಿಸಿ" ಕ್ಲಿಕ್ ಮಾಡುವ ಮೂಲಕ ನಿಮ್ಮ ಹೆಸರು, ಮೊಬೈಲ್ ಸಂಖ್ಯೆ, ವಿಳಾಸ, ಮತ್ತು ಎಲ್ಲಾ ಸಂತೆ ಜಾಹೀರಾತುಗಳನ್ನು ತಕ್ಷಣವೇ ಮತ್ತು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಬಹುದು.</p>
              </div>

              <div>
                <h3 className="text-lg font-bold mb-2">೫. ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ</h3>
                <p>ನಿಮ್ಮ ಗೌಪ್ಯತೆಗೆ ಸಂಬಂಧಿಸಿದ ಪ್ರಶ್ನೆಗಳಿಗಾಗಿ support@milkmaatu.com ಮೂಲಕ ಸಂಪರ್ಕಿಸಬಹುದು.</p>
              </div>
            </div>
          ) : (
            <div className="space-y-6 text-sm leading-relaxed">
              <p className="font-bold">Last Updated: June 7, 2026</p>
              <p>MilkMaatu is committed to protecting the privacy of dairy farmers in Karnataka. This Privacy Policy explains how we collect, use, and safe-guard your data.</p>
              
              <div>
                <h3 className="text-lg font-bold mb-2">1. Data We Collect</h3>
                <ul className="list-disc pl-5 space-y-1">
                  <li><strong>Personal Information:</strong> Name, mobile number, physical address, and village name during registration.</li>
                  <li><strong>Cattle Media:</strong> Live photos of your cattle captured directly via camera for Sante marketplace.</li>
                  <li><strong>AI Conversations:</strong> Transcripts of questions and messages sent to Nandini AI.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-lg font-bold mb-2">2. Why We Collect Data</h3>
                <ul className="list-disc pl-5 space-y-1">
                  <li>To verify user identity securely via WhatsApp OTP.</li>
                  <li>To coordinate feed shipping and facilitate Sante local cattle trades.</li>
                  <li>To optimize advisory suggestions generated by Nandini AI.</li>
                </ul>
              </div>

              <div>
                <h3 className="text-lg font-bold mb-2">3. Storage & Safety</h3>
                <p>All sensitive information, including passwords, is hashed securely using production-grade Bcrypt encryption and stored in PostgreSQL databases.</p>
              </div>

              <div>
                <h3 className="text-lg font-bold mb-2">4. User Rights & Deletion</h3>
                <p>You have full authority to request database deletion. By visiting the Profile page and clicking "Delete Account", all personal indicators, active listings, and session authorizations are completely removed and anonymized.</p>
              </div>

              <div>
                <h3 className="text-lg font-bold mb-2">5. Contact Support</h3>
                <p>For inquiries regarding data safety, reach us at support@milkmaatu.com.</p>
              </div>
            </div>
          )}
          <div className="mt-8 text-center">
            <Button variant="primary" onClick={() => navigate(-1)} className="px-8 font-bold">
              {t('common.back')}
            </Button>
          </div>
        </Card>
      </section>
    </div>
  );
};
